

--REGION BASE TABLE BUILD - NATIONAL BRAND ONLY
CREATE TABLE BRH_FULL_LOAD_BASE AS

SELECT /*+ parallel (16)*/ 
SYS_PLTFRM, 
BUS_PLTFRM, 
DIM_INV_DT_ID, 
JULIAN_DT, 
DT,
CUST_E1_NUM, 
PRCA_NUM, 
BILL_TO_CUST_E1_NUM,
ITEM_E1_NUM, 
ITEM_DSC,
SUM(EXT_NET_SLS_PROD_AMT) EXT_NET_SLS_PROD_AMT, 
SUM(EXT_SELL_GP_PROD_FIN_AMT) EXT_SELL_GP_PROD_FIN_AMT, 
SUM(INT_COST) EXT_INT_COST, 
CASE WHEN SHIP_QTY <> 0 THEN (INT_COST/SHIP_QTY) ELSE 0 END AVG_INT_COST, 
SUM(SHIP_QTY) SELL_QTY, 
SUPLR_ABBRV, 
SUPLR_DSC,
PRVT_BRND_FLG, 
ITEM_TYPE_CD, 
PROD_FMLY_LVL1_CD, 
PROD_FMLY_LVL1_DSC, 
PROD_CTGRY_LVL2_CD, 
PROD_CTGRY_LVL2_DSC, 
PROD_GRP_LVL3_CD, 
PROD_GRP_LVL3_DSC, 
PROD_SUB_CTGRY_LVL4_CD, 
PROD_SUB_CTGRY_LVL4_DSC,
PRC_TYPE_CD, PRC_TYPE_DSC, 
PRC_LVL_CD, 
MKT_CD, 
MKT_SGMNT_CD, 
CLASS_CD, 
CNTRCT_TYPE_CD, 
COMP_CTGRY_CD, 
SLS_GRP_CD,
CASE WHEN CLASS_DSC IN 'SURGERY CENTER' THEN 'PC-SC' WHEN CLASS_DSC IN 'LAB COMPANIES' THEN 'PC-LAB' ELSE 'PC-OTH' END COT_DSC
FROM(
SELECT /*+ parallel (16)*/ 
SLS.SLS_ID, 
SLS.SYS_PLTFRM, 
SLS.BUS_PLTFRM, 
SLS.DIM_INV_DT_ID,
PRD.JULIAN_DT, 
PRD.DT, 
SLS.SHIP_QTY,   
CUST.CUST_E1_NUM, 
CUST.PRCA_NUM, 
CUST.BILL_TO_CUST_E1_NUM,
ITM.ITEM_E1_NUM, 
SLS.EXT_NET_SLS_PROD_AMT, 
SLS.EXT_SELL_GP_PROD_FIN_AMT, 
SLS.EXT_TOS_CNTRCT_COST_AMT INT_COST, 
ITM.SUPLR_ABBRV, 
ITM.PRVT_BRND_FLG, 
ITM.ITEM_TYPE_CD, 
ITM.PROD_FMLY_LVL1_CD, 
ITM.PROD_FMLY_LVL1_DSC, 
ITM.PROD_CTGRY_LVL2_CD, 
ITM.PROD_CTGRY_LVL2_DSC,
ITM.PROD_GRP_LVL3_CD, 
ITM.PROD_GRP_LVL3_DSC, 
ITM.PROD_SUB_CTGRY_LVL4_CD, 
ITM.PROD_SUB_CTGRY_LVL4_DSC,
PRC.PRC_TYPE_CD, 
PRC.PRC_TYPE_DSC, 
PRC.PRC_LVL_CD, 
MKT.MKT_CD, 
MKT.MKT_SGMNT_CD, 
MKT.CLASS_CD, 
CRT.CNTRCT_TYPE_CD, 
MKT.CLASS_DSC, 
ITM.COMP_CTGRY_CD, 
ITM.SLS_GRP_CD,
ITM.ITEM_DSC, 
ITM.SUPLR_DSC    
FROM EDWRPT.V_FACT_SLS SLS
INNER JOIN EDWRPT.V_DIM_PERIOD PRD ON SLS.DIM_INV_DT_ID = PRD.DIM_PERIOD_ID
INNER JOIN EDWRPT.V_DIM_ITEM_LGCY_CURR IL ON SLS.DIM_ITEM_LGCY_CURR_ID = IL.DIM_ITEM_LGCY_CURR_ID 
INNER JOIN EDWRPT.V_DIM_ITEM_E1_CURR ITM ON IL.DIM_ITEM_E1_CURR_ID = ITM.DIM_ITEM_E1_CURR_ID
INNER JOIN EDWRPT.V_DIM_ITEM_LGCY_HIST IH ON SLS.DIM_ITEM_LGCY_HIST_ID = IH.DIM_ITEM_LGCY_HIST_ID
INNER JOIN EDWRPT.V_DIM_PRC_PROFILE PRC ON SLS.DIM_PRC_PROFILE_ID = PRC.DIM_PRC_PROFILE_ID
INNER JOIN EDWRPT.V_DIM_MKT MKT ON SLS.DIM_MKT_ID = MKT.DIM_MKT_ID AND SLS.SYS_PLTFRM = MKT.SYS_PLTFRM
INNER JOIN EDWRPT.V_DIM_CNTRCT CRT ON SLS.DIM_COST_CNTRCT_ID = CRT.DIM_CNTRCT_ID AND SLS.SYS_PLTFRM = CRT.SYS_PLTFRM AND PRD.DT BETWEEN CRT.CNTRCT_START_DT AND CRT.CNTRCT_END_DT
INNER JOIN EDWRPT.V_DIM_CUST_E1_BLEND_CURR CUST ON SLS.DIM_CUST_CURR_ID = CUST.DIM_CUST_CURR_ID AND SLS.SYS_PLTFRM = CUST.SYS_PLTFRM AND SLS.BUS_PLTFRM = CUST.BUS_PLTFRM
WHERE SLS.DIM_INV_DT_ID BETWEEN 20200801 AND 20210731 -- 001
AND ITM.SUPLR_ABBRV IN ('REPRMD','MDEFIL','ASMDSL','LIFESQ','LIFESN','LIFESQ','MDTECH','NEWRLD','GMAXIN','ALTSRC','SONOCO','SMTHOA',
'HOSPTX','AF','CRTRHD','ISOURC','BRKSHR','T-KENL','ETHORT','KENTRN','NEXSMD','VHACON','VHACON','CONCO','BRGCMT','SMTIMD','RPOCAR',
'DURLIF','DURLIF','NIDEKC','BYN007','ANCBSH','ACLINC','ACTVST','QMEDCN')
--AND SLS.BUS_PLTFRM IN 'PC'
AND CASE  WHEN SLS.PRMRY_UOM = '*' then 0
            when SLS.PRMRY_UOM = ITM.PRMRY_UOM then SLS.PRMRY_QTY / ITM.PRMRY_TO_SELL_DIVISOR
            when SLS.PRMRY_UOM = IH.PRMRY_UOM then SLS.PRMRY_QTY / IH.PRMRY_TO_E1_SELL_DIVISOR
            else 0
        END <> 0

)
GROUP BY SYS_PLTFRM, BUS_PLTFRM, DIM_INV_DT_ID, JULIAN_DT, DT,
CUST_E1_NUM, PRCA_NUM, BILL_TO_CUST_E1_NUM,
ITEM_E1_NUM, ITEM_DSC, SUPLR_DSC, 
SUPLR_ABBRV, PRVT_BRND_FLG, ITEM_TYPE_CD, PROD_FMLY_LVL1_CD, PROD_FMLY_LVL1_DSC, PROD_CTGRY_LVL2_CD, PROD_CTGRY_LVL2_DSC,PROD_GRP_LVL3_CD, PROD_GRP_LVL3_DSC, PROD_SUB_CTGRY_LVL4_CD, PROD_SUB_CTGRY_LVL4_DSC,
PRC_TYPE_CD, PRC_TYPE_DSC, PRC_LVL_CD, MKT_CD, MKT_SGMNT_CD, CLASS_CD, CNTRCT_TYPE_CD, CLASS_DSC, COMP_CTGRY_CD, SLS_GRP_CD,
CASE WHEN SHIP_QTY <> 0 THEN (INT_COST/SHIP_QTY) ELSE 0 END
;
--END REGION 



--REGION ALL MMS
CREATE TABLE BRH_FRT_LDS_MMS AS
SELECT /*+ parallel (16)*/ Y.*,

--CURRENT COST IMPACT/REASON
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 0
    WHEN SLS_GRP_CD IN '1234' THEN 0
    WHEN PPY55VENDE IN 'Y' THEN 0
    WHEN CNTRCT_TYPE_CD IN 'N/A' THEN NVL(EXT_INT_COST*(PPY55FRNC/1000000), 0)
    ELSE NVL(EXT_INT_COST*(PPY55FRC/1000000), 0) END FRT_COMP_IMP,
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 'DROP SHIP'
    WHEN SLS_GRP_CD IN '1234' THEN 'PRIVATE LABEL'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'W' THEN 'PREFERRED SUPPLIER' 
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'F' THEN 'PREFERRED FAMILY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'C' THEN 'PREFERRED CATEGORY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'G' THEN 'PREFERRED GROUP'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'I' THEN 'PREFERRED ITEM' 
    ELSE 'PASS TO COMP' END FRT_COMP_REASON,
--CURRENT PRC IMPACT/REASON
NVL(
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 0
    WHEN SLS_GRP_CD IN '1234' THEN 0 
    WHEN PPY55VENDE IN 'Y' THEN 0 
    WHEN Y.PRAA01 IN 'N' AND Y.CNTRCT_TYPE_CD NOT IN 'N/A' THEN 0 
    WHEN Y.PRAA02 IN 'N' AND Y.CNTRCT_TYPE_CD IN 'N/A' THEN 0 
    WHEN PRC_LVL_CD IN ('3','6','7','15','20','23','25', 'N/A') THEN 0
    WHEN CNTRCT_TYPE_CD IN 'N/A' THEN NVL(EXT_INT_COST*(PPY55FRNC/1000000), 0)  
    ELSE NVL(EXT_INT_COST*(PPY55FRC/1000000), 0) END, 0) FRT_PRC_IMP,
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 'DROP SHIP'
    WHEN SLS_GRP_CD IN '1234' THEN 'PRIVATE LABEL'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'W' THEN 'PREFERRED SUPPLIER' 
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'F' THEN 'PREFERRED FAMILY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'C' THEN 'PREFERRED CATEGORY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'G' THEN 'PREFERRED GROUP'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'I' THEN 'PREFERRED ITEM' 
    WHEN PRC_LVL_CD IN ('3','6','7','15','20','23','25', 'N/A') THEN 'PRICE LEVEL'
    WHEN Y.PRAA01 IN 'N' AND Y.CNTRCT_TYPE_CD NOT IN 'N/A' THEN 'REP EXCLUDE CONT' 
    WHEN Y.PRAA02 IN 'N' AND Y.CNTRCT_TYPE_CD IN 'N/A' THEN 'REP EXCLUDE NO CONT' 
    ELSE 'PASS TO PRICE' END FRT_PRC_REASON,
--HYP COMP IMPACT/REASON    
    CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 0
    --WHEN SLS_GRP_CD IN '1234' THEN 0
    WHEN PPY55VENDE IN 'Y' THEN 0
    ELSE NVL(EXT_INT_COST*(0.002404076), 0) END HYP_FRT_COMP_IMP,
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 'DROP SHIP'
    --WHEN SLS_GRP_CD IN '1234' THEN 'PRIVATE LABEL'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'W' THEN 'PREFERRED SUPPLIER' 
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'F' THEN 'PREFERRED FAMILY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'C' THEN 'PREFERRED CATEGORY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'G' THEN 'PREFERRED GROUP'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'I' THEN 'PREFERRED ITEM' 
    ELSE 'PASS TO COMP' END HYP_FRT_COMP_REASON,
 --HYP PRICE IMPACT/REASON       
    NVL(
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 0
    --WHEN SLS_GRP_CD IN '1234' THEN 0 
    WHEN PPY55VENDE IN 'Y' THEN 0 
    WHEN Y.PRAA01 IN 'N' AND Y.CNTRCT_TYPE_CD NOT IN 'N/A' THEN 0 
    WHEN Y.PRAA02 IN 'N' AND Y.CNTRCT_TYPE_CD IN 'N/A' THEN 0 
    WHEN PRC_LVL_CD IN ('3','6','7','15','20','23','25', 'N/A') THEN 0
    ELSE NVL(EXT_INT_COST*(0.002404076), 0) END, 0) HYP_FRT_PRC_IMP,
CASE 
    WHEN ITEM_TYPE_CD IN 'DS' THEN 'DROP SHIP'
    --WHEN SLS_GRP_CD IN '1234' THEN 'PRIVATE LABEL'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'W' THEN 'PREFERRED SUPPLIER' 
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'F' THEN 'PREFERRED FAMILY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'C' THEN 'PREFERRED CATEGORY'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'G' THEN 'PREFERRED GROUP'
    WHEN PPY55VENDE IN 'Y' AND PPTYRD IN 'I' THEN 'PREFERRED ITEM' 
    WHEN PRC_LVL_CD IN ('3','6','7','15','20','23','25', 'N/A') THEN 'PRICE LEVEL'
    WHEN Y.PRAA01 IN 'N' AND Y.CNTRCT_TYPE_CD NOT IN 'N/A' THEN 'REP EXCLUDE CONT' 
    WHEN Y.PRAA02 IN 'N' AND Y.CNTRCT_TYPE_CD IN 'N/A' THEN 'REP EXCLUDE NO CONT' 
    ELSE 'PASS TO PRICE' END HYP_FRT_PRC_REASON
FROM (
SELECT /*+ parallel (16)*/ A.*, LDSV.PPY55FRC, LDSV.PPY55FRNC, 
--COALESCE(LDSI.PPY55VENDE, LDSG.PPY55VENDE, LDSC.PPY55VENDE, LDSF.PPY55VENDE, LDSV.PPY55VENDE) PPY55VENDE, COALESCE(LDSI.PPTYRD, LDSG.PPTYRD, LDSC.PPTYRD, LDSF.PPTYRD, LDSV.PPTYRD) PPTYRD,    
COALESCE (
CASE WHEN LDSV.PPY55VENDE IN 'Y' THEN LDSV.PPTYRD ELSE NULL END,
CASE WHEN LDSF.PPY55VENDE IN 'Y' THEN LDSF.PPTYRD ELSE NULL END,
CASE WHEN LDSC90.PPY55VENDE IN 'Y' THEN LDSC90.PPTYRD ELSE NULL END,
CASE WHEN LDSC130.PPY55VENDE IN 'Y' THEN LDSC130.PPTYRD ELSE NULL END,
CASE WHEN LDSC170.PPY55VENDE IN 'Y' THEN LDSC170.PPTYRD ELSE NULL END,
CASE WHEN LDSG.PPY55VENDE IN 'Y' THEN LDSG.PPTYRD ELSE NULL END,
CASE WHEN LDSG2.PPY55VENDE IN 'Y' THEN LDSG2.PPTYRD ELSE NULL END,
CASE WHEN LDSI.PPY55VENDE IN 'Y' THEN LDSI.PPTYRD ELSE NULL END ) PPTYRD,
POP.PRAA01, POP.PRAA02, 
COALESCE (
CASE WHEN LDSV.PPY55VENDE IN 'Y' THEN LDSV.PPY55VENDE ELSE NULL END,
CASE WHEN LDSF.PPY55VENDE IN 'Y' THEN LDSF.PPY55VENDE ELSE NULL END,
CASE WHEN LDSC90.PPY55VENDE IN 'Y' THEN LDSC90.PPY55VENDE ELSE NULL END,
CASE WHEN LDSC130.PPY55VENDE IN 'Y' THEN LDSC130.PPY55VENDE ELSE NULL END,
CASE WHEN LDSC170.PPY55VENDE IN 'Y' THEN LDSC170.PPY55VENDE ELSE NULL END,
CASE WHEN LDSG.PPY55VENDE IN 'Y' THEN LDSG.PPY55VENDE ELSE NULL END,
CASE WHEN LDSG2.PPY55VENDE IN 'Y' THEN LDSG2.PPY55VENDE ELSE NULL END,
CASE WHEN LDSI.PPY55VENDE IN 'Y' THEN LDSI.PPY55VENDE ELSE NULL END ) PPY55VENDE,
CASE 
    WHEN LDSV.PPY55VENDE IN 'Y' THEN LDSV.PPDS01
    WHEN LDSF.PPY55VENDE IN 'Y' THEN LDSF.PPDS01
    WHEN LDSC90.PPY55VENDE IN 'Y' THEN LDSC90.PPDS01
    WHEN LDSC130.PPY55VENDE IN 'Y' THEN LDSC130.PPDS01
    WHEN LDSC170.PPY55VENDE IN 'Y' THEN LDSC170.PPDS01
    WHEN LDSG.PPY55VENDE IN 'Y' THEN LDSG.PPDS01
    WHEN LDSG2.PPY55VENDE IN 'Y' THEN LDSG2.PPDS01
    WHEN LDSI.PPY55VENDE IN 'Y' THEN LDSI.PPDS01 ELSE NULL
END FRT_COMP_NOTE  
FROM 
(SELECT * FROM BRH_FULL_LOAD_BASE UNION SELECT * FROM BRH_FULL_LOAD_BASE1) A 
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSI ON A.ITEM_E1_NUM = LDSI.PPITM AND A.BUS_PLTFRM = LDSI.PPY55CP AND A.JULIAN_DT BETWEEN LDSI.PPEFFF AND LDSI.PPEFFT AND LDSI.PPTYRD IN 'I'
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSV ON A.SUPLR_ABBRV = LDSV.PPPRVWABBR AND A.BUS_PLTFRM = LDSV.PPY55CP AND A.JULIAN_DT BETWEEN LDSV.PPEFFF AND LDSV.PPEFFT AND LDSV.PPTYRD IN 'W'
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSF ON A.PROD_FMLY_LVL1_CD = LDSF.PPY55PFAM AND A.BUS_PLTFRM = LDSF.PPY55CP AND A.JULIAN_DT BETWEEN LDSF.PPEFFF AND LDSF.PPEFFT AND LDSF.PPTYRD IN 'F'
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSC90 ON A.PROD_CTGRY_LVL2_CD = LDSC90.PPY55PCAT AND A.BUS_PLTFRM = LDSC90.PPY55CP AND A.JULIAN_DT BETWEEN LDSC90.PPEFFF AND LDSC90.PPEFFT AND LDSC90.PPTYRD IN 'C' AND A.SUPLR_ABBRV = LDSC90.PPPRVWABBR
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSC170 ON A.PROD_CTGRY_LVL2_CD = LDSC170.PPY55PCAT AND A.BUS_PLTFRM = LDSC170.PPY55CP AND A.JULIAN_DT BETWEEN LDSC170.PPEFFF AND LDSC170.PPEFFT AND LDSC170.PPTYRD IN 'C' AND LDSC170.PPSSQN = 170
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSC130 ON A.PROD_CTGRY_LVL2_CD = LDSC130.PPY55PCAT AND A.BUS_PLTFRM = LDSC130.PPY55CP AND A.JULIAN_DT BETWEEN LDSC130.PPEFFF AND LDSC130.PPEFFT AND LDSC130.PPTYRD IN 'C' AND LDSC130.PPSSQN = 130 AND LDSC130.PPAC02 = A.CLASS_CD
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSG ON A.PROD_GRP_LVL3_CD = LDSG.PPY55PGCD AND A.BUS_PLTFRM = LDSG.PPY55CP AND A.JULIAN_DT BETWEEN LDSG.PPEFFF AND LDSG.PPEFFT AND LDSG.PPTYRD IN 'G' AND LDSG.PPPRVWABBR = ' '
LEFT JOIN MMSDM910.SRC_E1_MMS_F552115 LDSG2 ON A.PROD_GRP_LVL3_CD = LDSG2.PPY55PGCD AND A.BUS_PLTFRM = LDSG2.PPY55CP AND A.SUPLR_ABBRV = LDSG2.PPPRVWABBR AND A.JULIAN_DT BETWEEN LDSG2.PPEFFF AND LDSG2.PPEFFT AND LDSG2.PPTYRD IN 'G'
LEFT JOIN MMSDM910.SRC_E1_MMS_F552015 POP ON A.PRCA_NUM = POP.PRAN8 AND A.JULIAN_DT BETWEEN POP.PREFFF AND POP.PREFFT
) Y
;
--END REGION

--REGION MMS_FULL_LOADS
CREATE TABLE BRH_FULL_LDS_MMS AS
SELECT  XX.*--, (XX.UNI_PRC_IMP + XX.STR_PRC_IMP + XX.FRT_PRC_IMP + XX.GPO_PRC_IMP /*+ XX.CUS_PRC_IMP*/ ) LD_PRC_IMP, (XX.UNI_COMP_IMP + XX.STR_COMP_IMP + XX.FRT_COMP_IMP + XX.GPO_COMP_IMP /*+ XX.CUS_COMP_IMP*/) LD_COMP_IMP
FROM (
SELECT  /*+ parallel (16)*/
       A.SYS_PLTFRM, A.BUS_PLTFRM, A.DIM_INV_DT_ID, 
       A.CUST_E1_NUM, A.PRCA_NUM, A.ITEM_E1_NUM,
       A.EXT_NET_SLS_PROD_AMT, A.EXT_INT_COST , A.AVG_INT_COST, 
       A.SUPLR_ABBRV, A.PRVT_BRND_FLG, A.ITEM_TYPE_CD, 
       A.PROD_FMLY_LVL1_CD, A.PROD_FMLY_LVL1_DSC, A.PROD_CTGRY_LVL2_CD, A.PROD_CTGRY_LVL2_DSC,
       A.PRC_TYPE_CD, A.PRC_TYPE_DSC, A.PRC_LVL_CD, A.MKT_CD, A.MKT_SGMNT_CD, A.CNTRCT_TYPE_CD, A.COMP_CTGRY_CD, A.COT_DSC,
       --C.GPO_NUM, C.GPO_NAME, C.PRGRM_NUM, C.PRGRM_DSC, C.SUB_PRGRM_NUM, C.SUB_PRGRM_DSC,
       ROUND(B.FRT_COMP_IMP,2) FRT_COMP_IMP,  B.FRT_COMP_REASON, ROUND(B.FRT_PRC_IMP,2) FRT_PRC_IMP, B.FRT_PRC_REASON,
       ROUND(B.HYP_FRT_COMP_IMP,2) HYP_FRT_COMP_IMP,  B.HYP_FRT_COMP_REASON, ROUND(B.HYP_FRT_PRC_IMP,2) HYP_FRT_PRC_IMP, B.HYP_FRT_PRC_REASON
      
from (SELECT * FROM BRH_FULL_LOAD_BASE UNION SELECT * FROM BRH_FULL_LOAD_BASE1) A  
                                              INNER JOIN BRH_FRT_LDS_MMS B ON A.BUS_PLTFRM = B.BUS_PLTFRM
                                              AND A.CUST_E1_NUM = B.CUST_E1_NUM
                                              AND A.DT = B.DT
                                              AND A.ITEM_E1_NUM = B.ITEM_E1_NUM
                                              AND A.SYS_PLTFRM = B.SYS_PLTFRM                              
) XX
;
--END REGION 


--ALL MMS
SELECT BRH_FULL_LDS_MMS.HYP_FRT_PRC_REASON ,
SUM(BRH_FULL_LDS_MMS.HYP_FRT_COMP_IMP) HYP_FRT_COMP_IMP, SUM(BRH_FULL_LDS_MMS.HYP_FRT_PRC_IMP) HYP_FRT_PRC_IMP
FROM BRH_FULL_LDS_MMS
GROUP BY BRH_FULL_LDS_MMS.HYP_FRT_PRC_REASON

